apiVersion: apps/v1
kind: Deployment
metadata:
  # deployment name
  name: node-deployment
  labels:
    app: node
spec:
  # modify replicas according to your case
  replicas: 1
  selector:
    matchLabels:
      app: node    
  # pod template
  template:
    metadata:
      labels:
        app: node
    spec:
      # pod contains 1 container
      containers:
      - name: node
        image: kanolanacr.azurecr.io/nodejs-server:latest
        livenessProbe:
          httpGet:
            path: /
            port: 22137
          initialDelaySeconds: 30
          timeoutSeconds: 1
          periodSeconds: 10
          failureThreshold: 3 
        livenessProbe:
          httpGet:
            path: /
            port: 22137
          periodSeconds: 10
          failureThreshold: 3 
          successThreshold: 1 
        # container opens port 22137
        ports:
        - containerPort: 22137
          name: http
          protocol: TCP            
---
apiVersion: v1
kind: Service
metadata:
  # The unique Service instance/name
  name: node-service
spec:
  # Add external load balancer
  # *Only supported by some cloud providers*
  type: LoadBalancer
  ports:
    - name: http
      port: 22137
      targetPort: 22137
  selector:
    # Loadbalance traffic across Pods matching
    # this label selector
    app: node
