---
name: "TF workflow"

'on':
  push:
    branches:
      - main
    tags:
      - "*"
  pull_request:
    branches:
      - main

jobs:
  terraformtasks:
    name: "Terraform Tasks"
    runs-on: "ubuntu-latest"
    steps: 
      - name: "Checkout Code"
        uses: "actions/checkout@v2"    
        
      #name: "Setup Terraform"
      - uses: hashicorp/setup-terraform@v2
      - run: terraform init
      - id: plan
          run: terraform plan -no-color
        - run: echo ${{ steps.plan.outputs.stdout }}
        - run: echo ${{ steps.plan.outputs.stderr }}
        - run: echo ${{ steps.plan.outputs.exitcode }}
        